/**
 * EVENT_REGISTRY and ALERT_POLICIES (api-contracts §3, event-pipeline §7): the single source of truth for
 * the `event_types` and `alert_policies` tables (generated by scripts/gen-sql-seed.ts, checked by B4's test).
 */
import { z } from "zod";
import type { AlertKind, AlertTier, Audience } from "./enums";
import { AlertAcknowledged, AlertEscalated, AlertResolved, AlertRaised, AlertSuppressed, AnomalyDetected,
  AnomalyRef, DispatchUpdate, EventEnvelopeBase, FrameSeq, GuardianHazard, IncidentLogged, IncidentReported,
  LedgerCheckResult, LedgerCheckpoint, LessonAssigned, LessonCompleted, MotionLockChanged, OrganiserAlert,
  Overspeed, PpeMissing, PpeOverride, PpeRestored, Proximity, ReplayCompleted, ReplayReady, ScenarioChange,
  SeatbeltBreach, SlopeExceeded, SosCancelled, SosRaised, SystemWarning, TaskChange } from "./events";

export type EventMeta = {
  tier: AlertTier | null;
  ledger: boolean;            // true → the event trigger enqueues a ledger entry (the only ledger write path, N3)
  alert_kind: AlertKind | null; // non-null → raise_alert with this kind
  audiences: readonly Audience[];
  lesson_code: string | null; // non-null → Loop assigns this lesson (via private.loop_queue, N2)
  replay: boolean;            // true → build_replay from this event
};
export type RegistryEntry<P extends z.ZodType = z.ZodType> = EventMeta & { payload: P };

const r = <P extends z.ZodType>(payload: P, m: Partial<EventMeta> & Pick<EventMeta, "audiences">): RegistryEntry<P> =>
  ({ payload, tier: null, ledger: false, alert_kind: null, lesson_code: null, replay: false, ...m });
const OP_SUP = ["operator", "supervisor"] as const;
const SITE_SUP = ["site", "supervisor"] as const;

export const EVENT_REGISTRY = {
  "safety.seatbelt_breach":   r(SeatbeltBreach, { tier: "warning", ledger: true, alert_kind: "seatbelt_off_moving",
                                 audiences: [...OP_SUP, "trainer"], lesson_code: "seatbelt_slopes", replay: true }), // P0 replay (demo beat 4)
  "safety.seatbelt_resolved": r(FrameSeq, { audiences: [...OP_SUP] }),
  "safety.overspeed":         r(Overspeed, { tier: "caution", audiences: [...OP_SUP] }),   // event only in P0, no alert
  "safety.slope_exceeded":    r(SlopeExceeded, { tier: "warning", audiences: [...OP_SUP, "trainer"] }),
  "safety.proximity":         r(Proximity, { tier: "caution", alert_kind: "proximity_zone", audiences: [...OP_SUP] }),
  "safety.organiser_alert":   r(OrganiserAlert, { tier: "info", audiences: ["supervisor"] }),
  "anomaly.detected":         r(AnomalyDetected, { tier: "caution", alert_kind: "anomaly_machine", audiences: [...SITE_SUP] }),
  "anomaly.cleared":          r(AnomalyRef, { audiences: [...SITE_SUP] }),
  "guardian.hazard_near_operator": r(GuardianHazard, { tier: "warning", ledger: true, alert_kind: "guardian_hazard",
                                 audiences: [...OP_SUP, "trainer"], lesson_code: "faulty_machine_nearby" }), // replay P1
  "guardian.hazard_cleared":  r(AnomalyRef, { audiences: [...OP_SUP] }),
  "alert.raised":             r(AlertRaised, { audiences: [...OP_SUP] }),
  "alert.acknowledged":       r(AlertAcknowledged, { audiences: [...OP_SUP] }),
  "alert.escalated":          r(AlertEscalated, { audiences: [...OP_SUP] }),
  "alert.resolved":           r(AlertResolved, { audiences: [...OP_SUP] }),
  "alert.suppressed":         r(AlertSuppressed, { audiences: ["supervisor"] }),
  "dispatch.sent":            r(DispatchUpdate, { audiences: [...OP_SUP] }),   // operator = alert owner (UI-10)
  "dispatch.delivered":       r(DispatchUpdate, { audiences: [...OP_SUP] }),
  "dispatch.answered":        r(DispatchUpdate, { audiences: [...OP_SUP] }),
  "dispatch.failed":          r(DispatchUpdate, { audiences: [...OP_SUP] }),
  "dispatch.suppressed":      r(DispatchUpdate, { audiences: [...OP_SUP] }),
  "sos.raised":               r(SosRaised, { tier: "critical", ledger: true, alert_kind: "sos", audiences: [...OP_SUP] }),
  "sos.cancelled":            r(SosCancelled, { audiences: [...OP_SUP] }),
  "ppe.missing":              r(PpeMissing, { tier: "caution", alert_kind: "ppe_missing", audiences: [...OP_SUP] }),
  "ppe.restored":             r(PpeRestored, { audiences: [...OP_SUP] }),
  "ppe.override_granted":     r(PpeOverride, { ledger: true, audiences: [...OP_SUP] }),
  "task.started":             r(TaskChange, { audiences: [...OP_SUP] }),
  "task.paused":              r(TaskChange, { audiences: [...OP_SUP] }),
  "task.completed":           r(TaskChange, { audiences: [...OP_SUP] }),
  "task.progress":            r(TaskChange, { audiences: [...OP_SUP] }),
  "task.start_blocked":       r(PpeMissing, { audiences: [...OP_SUP] }),
  "incident.reported":        r(IncidentReported, { ledger: true, audiences: [...OP_SUP] }),   // incident_log RPC (N3 single path)
  "incident.logged":          r(IncidentLogged, { audiences: [...OP_SUP] }),
  "operator.motion_lock_changed": r(MotionLockChanged, { audiences: ["operator"] }),          // UI-5
  "ledger.verified":          r(LedgerCheckResult, { audiences: ["supervisor"] }),
  "ledger.tamper_detected":   r(LedgerCheckResult, { tier: "critical", alert_kind: "ledger_tamper", audiences: ["supervisor"] }),
  "ledger.checkpoint_published": r(LedgerCheckpoint, { audiences: ["supervisor"] }),
  "training.lesson_assigned": r(LessonAssigned, { audiences: ["operator", "trainer"] }),
  "training.lesson_completed": r(LessonCompleted, { audiences: ["operator", "trainer"] }),
  "training.replay_ready":    r(ReplayReady, { audiences: ["operator", "trainer"] }),
  "training.replay_completed": r(ReplayCompleted, { audiences: ["operator", "trainer"] }),
  "scenario.started":         r(ScenarioChange, { audiences: ["site"] }),
  "scenario.paused":          r(ScenarioChange, { audiences: ["site"] }),
  "scenario.resumed":         r(ScenarioChange, { audiences: ["site"] }),
  "scenario.speed_changed":   r(ScenarioChange, { audiences: ["site"] }),
  "scenario.jumped":          r(ScenarioChange, { audiences: ["site"] }),
  "scenario.finished":        r(ScenarioChange, { audiences: ["site"] }),
  "system.warning":           r(SystemWarning, { audiences: ["supervisor"] }),
} as const satisfies Record<string, RegistryEntry>;

export type EventType = keyof typeof EVENT_REGISTRY;
export const EVENT_TYPES = Object.keys(EVENT_REGISTRY) as EventType[];

/** Envelope + the payload schema of one registered type (keeps that type's own payload, so `type` narrows `payload`). */
export function eventSchema<T extends EventType>(type: T) {
  const payload = EVENT_REGISTRY[type].payload as (typeof EVENT_REGISTRY)[T]["payload"];
  return EventEnvelopeBase.extend({ type: z.literal(type), payload });
}
type EventSchemaOf<T extends EventType> = ReturnType<typeof eventSchema<T>>;
type EventSchemaTuple = [EventSchemaOf<EventType>, ...EventSchemaOf<EventType>[]];
/** Discriminated union over every registered type. Unknown types are rendered generically by the UI (`GenericEvent`). */
export const AnyEvent = z.discriminatedUnion("type", EVENT_TYPES.map((t) => eventSchema(t)) as EventSchemaTuple);
export type AnyEvent = z.infer<typeof AnyEvent>;

/**
 * Alert budget seed (event-pipeline §7). `notify_now` fires on raise; `escalate_to` fires when the ack
 * timeout lapses (`escalation_level` 1). Windows are wall-clock. SOS never deduplicates (G2-3).
 */
export type AlertPolicy = {
  hazard_group: string;
  tier_default: AlertTier;
  tier_max: AlertTier;            // the in-place upgrade ceiling (e.g. critical on a slope / < 15 m)
  dedupe_window_s: number | null; // null = never merged (SOS)
  ack_timeout_s: number | null;   // null = no acknowledgement expected
  notify_now: readonly ("supervisor_telegram" | "operator_call" | "supervisor_call")[];
  escalate_to: readonly ("supervisor_telegram" | "operator_call" | "supervisor_call")[];
  rate_capped: boolean;           // only info/caution kinds may be capped
};
export const ALERT_POLICIES = {
  seatbelt_off_moving: { hazard_group: "seatbelt", tier_default: "warning", tier_max: "critical", dedupe_window_s: 120,
    ack_timeout_s: 20, notify_now: [], escalate_to: ["supervisor_telegram"], rate_capped: false },
  guardian_hazard:     { hazard_group: "guardian", tier_default: "warning", tier_max: "critical", dedupe_window_s: 60,
    ack_timeout_s: 15, notify_now: [], escalate_to: ["operator_call", "supervisor_telegram"], rate_capped: false },
  proximity_zone:      { hazard_group: "proximity", tier_default: "caution", tier_max: "warning", dedupe_window_s: 30,
    ack_timeout_s: 20, notify_now: [], escalate_to: ["supervisor_telegram"], rate_capped: true },
  ppe_missing:         { hazard_group: "ppe", tier_default: "caution", tier_max: "caution", dedupe_window_s: 300,
    ack_timeout_s: null, notify_now: [], escalate_to: [], rate_capped: true },
  anomaly_machine:     { hazard_group: "machine_health", tier_default: "caution", tier_max: "caution", dedupe_window_s: 600,
    ack_timeout_s: null, notify_now: [], escalate_to: [], rate_capped: true },
  idle_excess:         { hazard_group: "idle", tier_default: "info", tier_max: "caution", dedupe_window_s: 1800,
    ack_timeout_s: null, notify_now: [], escalate_to: [], rate_capped: true },
  sos:                 { hazard_group: "sos", tier_default: "critical", tier_max: "critical", dedupe_window_s: null,
    ack_timeout_s: 60, notify_now: ["supervisor_telegram"], escalate_to: ["supervisor_call"], rate_capped: false },
  ledger_tamper:       { hazard_group: "ledger", tier_default: "critical", tier_max: "critical", dedupe_window_s: 600,
    ack_timeout_s: null, notify_now: ["supervisor_telegram"], escalate_to: [], rate_capped: false },
  alert_flood:         { hazard_group: "flood", tier_default: "caution", tier_max: "caution", dedupe_window_s: 600,
    ack_timeout_s: null, notify_now: ["supervisor_telegram"], escalate_to: [], rate_capped: false },
} as const satisfies Record<AlertKind, AlertPolicy>;
