-- GENERATED by scripts/gen-sql-seed.ts from @cat/shared (contracts). Do not edit by hand.

insert into public.event_types (type, default_tier, ledger, raises_alert, alert_kind, audiences, lesson_code, replay) values
  ('safety.seatbelt_breach', 'warning'::public.alert_tier, true, true, 'seatbelt_off_moving', array['operator', 'supervisor', 'trainer']::public.audience[], 'seatbelt_slopes', true),
  ('safety.seatbelt_resolved', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('safety.overspeed', 'caution'::public.alert_tier, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('safety.slope_exceeded', 'warning'::public.alert_tier, false, false, null, array['operator', 'supervisor', 'trainer']::public.audience[], null, false),
  ('safety.proximity', 'caution'::public.alert_tier, false, true, 'proximity_zone', array['operator', 'supervisor']::public.audience[], null, false),
  ('safety.organiser_alert', 'info'::public.alert_tier, false, false, null, array['supervisor']::public.audience[], null, false),
  ('anomaly.detected', 'caution'::public.alert_tier, false, true, 'anomaly_machine', array['site', 'supervisor']::public.audience[], null, false),
  ('anomaly.cleared', null, false, false, null, array['site', 'supervisor']::public.audience[], null, false),
  ('guardian.hazard_near_operator', 'warning'::public.alert_tier, true, true, 'guardian_hazard', array['operator', 'supervisor', 'trainer']::public.audience[], 'faulty_machine_nearby', false),
  ('guardian.hazard_cleared', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.raised', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.acknowledged', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.escalated', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.resolved', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.suppressed', null, false, false, null, array['supervisor']::public.audience[], null, false),
  ('dispatch.sent', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.delivered', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.answered', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.failed', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.suppressed', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('sos.raised', 'critical'::public.alert_tier, true, true, 'sos', array['operator', 'supervisor']::public.audience[], null, false),
  ('sos.cancelled', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('ppe.missing', 'caution'::public.alert_tier, false, true, 'ppe_missing', array['operator', 'supervisor']::public.audience[], null, false),
  ('ppe.restored', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('ppe.override_granted', null, true, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.started', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.paused', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.completed', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.progress', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.start_blocked', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('incident.reported', null, true, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('incident.logged', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('operator.motion_lock_changed', null, false, false, null, array['operator']::public.audience[], null, false),
  ('ledger.verified', null, false, false, null, array['supervisor']::public.audience[], null, false),
  ('ledger.tamper_detected', 'critical'::public.alert_tier, false, true, 'ledger_tamper', array['supervisor']::public.audience[], null, false),
  ('ledger.checkpoint_published', null, false, false, null, array['supervisor']::public.audience[], null, false),
  ('training.lesson_assigned', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('training.lesson_completed', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('training.replay_ready', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('training.replay_completed', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('scenario.started', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.paused', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.resumed', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.speed_changed', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.jumped', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.finished', null, false, false, null, array['site']::public.audience[], null, false),
  ('system.warning', null, false, false, null, array['supervisor']::public.audience[], null, false)
on conflict (type) do update set default_tier = excluded.default_tier, ledger = excluded.ledger,
  raises_alert = excluded.raises_alert, alert_kind = excluded.alert_kind, audiences = excluded.audiences,
  lesson_code = excluded.lesson_code, replay = excluded.replay;
delete from public.event_types where type <> all (array['safety.seatbelt_breach', 'safety.seatbelt_resolved', 'safety.overspeed', 'safety.slope_exceeded', 'safety.proximity', 'safety.organiser_alert', 'anomaly.detected', 'anomaly.cleared', 'guardian.hazard_near_operator', 'guardian.hazard_cleared', 'alert.raised', 'alert.acknowledged', 'alert.escalated', 'alert.resolved', 'alert.suppressed', 'dispatch.sent', 'dispatch.delivered', 'dispatch.answered', 'dispatch.failed', 'dispatch.suppressed', 'sos.raised', 'sos.cancelled', 'ppe.missing', 'ppe.restored', 'ppe.override_granted', 'task.started', 'task.paused', 'task.completed', 'task.progress', 'task.start_blocked', 'incident.reported', 'incident.logged', 'operator.motion_lock_changed', 'ledger.verified', 'ledger.tamper_detected', 'ledger.checkpoint_published', 'training.lesson_assigned', 'training.lesson_completed', 'training.replay_ready', 'training.replay_completed', 'scenario.started', 'scenario.paused', 'scenario.resumed', 'scenario.speed_changed', 'scenario.jumped', 'scenario.finished', 'system.warning']::text[]);

insert into public.alert_policies (kind, hazard_group, tier_default, tier_max, dedupe_window_s, ack_timeout_s, notify_now, escalate_to, rate_capped, needs_ack) values
  ('seatbelt_off_moving', 'seatbelt', 'warning'::public.alert_tier, 'critical'::public.alert_tier, 120, 20, '{}'::text[], array['supervisor_telegram']::text[], false, true),
  ('guardian_hazard', 'guardian', 'warning'::public.alert_tier, 'critical'::public.alert_tier, 60, 15, '{}'::text[], array['operator_call', 'supervisor_telegram']::text[], false, true),
  ('proximity_zone', 'proximity', 'caution'::public.alert_tier, 'warning'::public.alert_tier, 30, 20, '{}'::text[], array['supervisor_telegram']::text[], true, true),
  ('ppe_missing', 'ppe', 'caution'::public.alert_tier, 'caution'::public.alert_tier, 300, null, '{}'::text[], '{}'::text[], true, false),
  ('anomaly_machine', 'machine_health', 'caution'::public.alert_tier, 'caution'::public.alert_tier, 600, null, '{}'::text[], '{}'::text[], true, false),
  ('idle_excess', 'idle', 'info'::public.alert_tier, 'caution'::public.alert_tier, 1800, null, '{}'::text[], '{}'::text[], true, false),
  ('sos', 'sos', 'critical'::public.alert_tier, 'critical'::public.alert_tier, null, 60, array['supervisor_telegram']::text[], array['supervisor_call']::text[], false, true),
  ('ledger_tamper', 'ledger', 'critical'::public.alert_tier, 'critical'::public.alert_tier, 600, null, array['supervisor_telegram']::text[], '{}'::text[], false, false),
  ('alert_flood', 'flood', 'caution'::public.alert_tier, 'caution'::public.alert_tier, 600, null, array['supervisor_telegram']::text[], '{}'::text[], false, false)
on conflict (kind) do update set hazard_group = excluded.hazard_group, tier_default = excluded.tier_default,
  tier_max = excluded.tier_max, dedupe_window_s = excluded.dedupe_window_s, ack_timeout_s = excluded.ack_timeout_s,
  notify_now = excluded.notify_now, escalate_to = excluded.escalate_to, rate_capped = excluded.rate_capped, needs_ack = excluded.needs_ack;
delete from public.alert_policies where kind <> all (array['seatbelt_off_moving', 'guardian_hazard', 'proximity_zone', 'ppe_missing', 'anomaly_machine', 'idle_excess', 'sos', 'ledger_tamper', 'alert_flood']::text[]);

insert into public.explanation_templates (anomaly_type, en, hi) values
  ('idle_excess'::public.anomaly_type, '{machine} idled {idle_pct}% of the last hour, {ratio}× its normal. About {fuel_l} L of diesel (≈ ₹{cost_inr}).', '{machine} पिछले एक घंटे में {idle_pct}% समय खाली चली, सामान्य से {ratio} गुना। लगभग {fuel_l} लीटर डीज़ल (≈ ₹{cost_inr})।'),
  ('seatbelt_off_moving'::public.anomaly_type, '{machine} moved at {speed_kmh} km/h with the seatbelt off on a {pitch_deg}° slope.', '{machine} {pitch_deg}° ढलान पर बिना सीटबेल्ट {speed_kmh} किमी/घंटा चली।'),
  ('overspeed'::public.anomaly_type, '{machine} ran at {speed_kmh} km/h in a {limit_kmh} km/h zone.', '{machine} {limit_kmh} किमी/घंटा ज़ोन में {speed_kmh} किमी/घंटा चली।'),
  ('slope_exceeded'::public.anomaly_type, '{machine} worked on a {pitch_deg}° slope; the limit is {limit_deg}°.', '{machine} {pitch_deg}° ढलान पर चली; सीमा {limit_deg}° है।'),
  ('fault_continued_operation'::public.anomaly_type, '{machine} kept working for {minutes} min with fault {code} active.', '{machine} फ़ॉल्ट {code} के साथ {minutes} मिनट चलती रही।'),
  ('hydraulic_temp_drift'::public.anomaly_type, '{machine} hydraulic oil is at {value}°C, rising above its normal {mean}°C.', '{machine} का हाइड्रोलिक तेल {value}°C है, सामान्य {mean}°C से ऊपर।'),
  ('coolant_temp_drift'::public.anomaly_type, '{machine} coolant is at {value}°C, above its normal {mean}°C.', '{machine} का कूलेंट {value}°C है, सामान्य {mean}°C से ऊपर।')
on conflict (anomaly_type) do update set en = excluded.en, hi = excluded.hi;
