/**
 * SQL generated from the contracts (api-contracts §0 rule 2, G2-9): the Postgres enums, the `event_types`
 * and `alert_policies` seeds and the anomaly explanation templates. Nothing in SQL is hand-written for
 * these lists; B4's sqltest compares the tables with the registry.
 */
import { ALERT_POLICIES, EVENT_REGISTRY, EXPLANATION_TEMPLATES, SQL_ENUMS } from "../../packages/shared/src/index.ts";

export const GENERATED_HEADER = "-- GENERATED by scripts/gen-sql-seed.ts from @cat/shared (contracts). Do not edit by hand.";
export const BEGIN_MARK = "-- >>> generated: contracts seed (do not edit between the markers)";
export const END_MARK = "-- <<< generated: contracts seed";

/** SQL string literal: the only escaping needed is `'` → `''`; UTF-8 text such as Devanagari is emitted raw. */
export const sqlLiteral = (s: string) => `'${s.replace(/'/g, "''")}'`;
const lit = sqlLiteral;
const litOrNull = (s: string | null) => (s === null ? "null" : lit(s));
const numOrNull = (n: number | null) => (n === null ? "null" : String(n));
const textArray = (xs: readonly string[]) => (xs.length ? `array[${xs.map(lit).join(", ")}]::text[]` : "'{}'::text[]");

/**
 * `create type public.<name> as enum (…)` (duplicate_object ignored) followed by one
 * `alter type … add value if not exists` per value, so a value added to the contracts after the freeze
 * reaches an existing database on the next run (enum values are additive; removals need a migration).
 */
export function enumsSql(): string {
  const lines = [GENERATED_HEADER,
    "-- Enum values are additive after the contracts freeze; `add value if not exists` keeps existing types current.", ""];
  for (const [name, schema] of Object.entries(SQL_ENUMS)) {
    const values = schema.options.map(lit).join(", ");
    lines.push("do $$ begin", `  create type public.${name} as enum (${values});`, "exception when duplicate_object then null; end $$;");
    for (const v of schema.options) lines.push(`alter type public.${name} add value if not exists ${lit(v)};`);
    lines.push("");
  }
  return lines.join("\n");
}

/** Upserts for event_types, alert_policies and explanation_templates, and deletion of rows no longer in the registry. */
export function registrySeedSql(): string {
  const lines = [GENERATED_HEADER, ""];
  const types = Object.keys(EVENT_REGISTRY);
  lines.push("insert into public.event_types (type, default_tier, ledger, raises_alert, alert_kind, audiences, lesson_code, replay) values");
  lines.push(Object.entries(EVENT_REGISTRY).map(([type, m]) =>
    `  (${lit(type)}, ${litOrNull(m.tier)}${m.tier ? "::public.alert_tier" : ""}, ${m.ledger}, ${m.alert_kind !== null}, ${litOrNull(m.alert_kind)}, ` +
    `array[${m.audiences.map(lit).join(", ")}]::public.audience[], ${litOrNull(m.lesson_code)}, ${m.replay})`).join(",\n"));
  lines.push("on conflict (type) do update set default_tier = excluded.default_tier, ledger = excluded.ledger,",
    "  raises_alert = excluded.raises_alert, alert_kind = excluded.alert_kind, audiences = excluded.audiences,",
    "  lesson_code = excluded.lesson_code, replay = excluded.replay;");
  lines.push(`delete from public.event_types where type <> all (${textArray(types)});`, "");

  lines.push("insert into public.alert_policies (kind, hazard_group, tier_default, tier_max, dedupe_window_s, ack_timeout_s, notify_now, escalate_to, rate_capped, needs_ack) values");
  lines.push(Object.entries(ALERT_POLICIES).map(([kind, p]) =>
    `  (${lit(kind)}, ${lit(p.hazard_group)}, ${lit(p.tier_default)}::public.alert_tier, ${lit(p.tier_max)}::public.alert_tier, ` +
    `${numOrNull(p.dedupe_window_s)}, ${numOrNull(p.ack_timeout_s)}, ${textArray(p.notify_now)}, ${textArray(p.escalate_to)}, ` +
    `${p.rate_capped}, ${p.ack_timeout_s !== null})`).join(",\n"));
  lines.push("on conflict (kind) do update set hazard_group = excluded.hazard_group, tier_default = excluded.tier_default,",
    "  tier_max = excluded.tier_max, dedupe_window_s = excluded.dedupe_window_s, ack_timeout_s = excluded.ack_timeout_s,",
    "  notify_now = excluded.notify_now, escalate_to = excluded.escalate_to, rate_capped = excluded.rate_capped, needs_ack = excluded.needs_ack;");
  lines.push(`delete from public.alert_policies where kind <> all (${textArray(Object.keys(ALERT_POLICIES))});`, "");

  lines.push("insert into public.explanation_templates (anomaly_type, en, hi) values");
  lines.push(Object.entries(EXPLANATION_TEMPLATES).map(([t, tpl]) =>
    `  (${lit(t)}::public.anomaly_type, ${lit(tpl.en)}, ${lit(tpl.hi)})`).join(",\n"));
  lines.push("on conflict (anomaly_type) do update set en = excluded.en, hi = excluded.hi;", "");
  return lines.join("\n");
}

/** Replaces the block between the markers in a migration file, or appends the block if the markers are absent. */
export function embedSeed(migrationText: string, seed: string): string {
  const block = `${BEGIN_MARK}\n${seed.trim()}\n${END_MARK}`;
  const start = migrationText.indexOf(BEGIN_MARK);
  const end = migrationText.indexOf(END_MARK);
  if (start >= 0 && end > start) return migrationText.slice(0, start) + block + migrationText.slice(end + END_MARK.length);
  return `${migrationText.trimEnd()}\n\n${block}\n`;
}
