-- GENERATED by scripts/gen-sql-seed.ts from @cat/shared (contracts). Do not edit by hand.
-- Enum values are additive after the contracts freeze; `add value if not exists` keeps existing types current.

do $$ begin
  create type public.app_role as enum ('operator', 'fleet_manager', 'trainer');
exception when duplicate_object then null; end $$;
alter type public.app_role add value if not exists 'operator';
alter type public.app_role add value if not exists 'fleet_manager';
alter type public.app_role add value if not exists 'trainer';

do $$ begin
  create type public.audience as enum ('operator', 'site', 'supervisor', 'trainer');
exception when duplicate_object then null; end $$;
alter type public.audience add value if not exists 'operator';
alter type public.audience add value if not exists 'site';
alter type public.audience add value if not exists 'supervisor';
alter type public.audience add value if not exists 'trainer';

do $$ begin
  create type public.alert_tier as enum ('info', 'caution', 'warning', 'critical');
exception when duplicate_object then null; end $$;
alter type public.alert_tier add value if not exists 'info';
alter type public.alert_tier add value if not exists 'caution';
alter type public.alert_tier add value if not exists 'warning';
alter type public.alert_tier add value if not exists 'critical';

do $$ begin
  create type public.skill_level as enum ('novice', 'intermediate', 'expert');
exception when duplicate_object then null; end $$;
alter type public.skill_level add value if not exists 'novice';
alter type public.skill_level add value if not exists 'intermediate';
alter type public.skill_level add value if not exists 'expert';

do $$ begin
  create type public.task_type as enum ('excavation', 'trenching', 'material_loading', 'grading', 'demolition');
exception when duplicate_object then null; end $$;
alter type public.task_type add value if not exists 'excavation';
alter type public.task_type add value if not exists 'trenching';
alter type public.task_type add value if not exists 'material_loading';
alter type public.task_type add value if not exists 'grading';
alter type public.task_type add value if not exists 'demolition';

do $$ begin
  create type public.task_status as enum ('planned', 'in_progress', 'paused', 'completed', 'cancelled', 'blocked_ppe');
exception when duplicate_object then null; end $$;
alter type public.task_status add value if not exists 'planned';
alter type public.task_status add value if not exists 'in_progress';
alter type public.task_status add value if not exists 'paused';
alter type public.task_status add value if not exists 'completed';
alter type public.task_status add value if not exists 'cancelled';
alter type public.task_status add value if not exists 'blocked_ppe';

do $$ begin
  create type public.weather_kind as enum ('clear', 'hot', 'rain', 'windy', 'cold', 'fog', 'dust');
exception when duplicate_object then null; end $$;
alter type public.weather_kind add value if not exists 'clear';
alter type public.weather_kind add value if not exists 'hot';
alter type public.weather_kind add value if not exists 'rain';
alter type public.weather_kind add value if not exists 'windy';
alter type public.weather_kind add value if not exists 'cold';
alter type public.weather_kind add value if not exists 'fog';
alter type public.weather_kind add value if not exists 'dust';

do $$ begin
  create type public.fault_severity as enum ('info', 'caution', 'derate', 'shutdown');
exception when duplicate_object then null; end $$;
alter type public.fault_severity add value if not exists 'info';
alter type public.fault_severity add value if not exists 'caution';
alter type public.fault_severity add value if not exists 'derate';
alter type public.fault_severity add value if not exists 'shutdown';

do $$ begin
  create type public.run_status as enum ('ready', 'playing', 'paused', 'finished');
exception when duplicate_object then null; end $$;
alter type public.run_status add value if not exists 'ready';
alter type public.run_status add value if not exists 'playing';
alter type public.run_status add value if not exists 'paused';
alter type public.run_status add value if not exists 'finished';

do $$ begin
  create type public.frame_kind as enum ('telemetry', 'gps', 'operator_state', 'weather', 'fault', 'ppe');
exception when duplicate_object then null; end $$;
alter type public.frame_kind add value if not exists 'telemetry';
alter type public.frame_kind add value if not exists 'gps';
alter type public.frame_kind add value if not exists 'operator_state';
alter type public.frame_kind add value if not exists 'weather';
alter type public.frame_kind add value if not exists 'fault';
alter type public.frame_kind add value if not exists 'ppe';

do $$ begin
  create type public.alert_status as enum ('open', 'acknowledged', 'escalating', 'escalated', 'resolved', 'suppressed');
exception when duplicate_object then null; end $$;
alter type public.alert_status add value if not exists 'open';
alter type public.alert_status add value if not exists 'acknowledged';
alter type public.alert_status add value if not exists 'escalating';
alter type public.alert_status add value if not exists 'escalated';
alter type public.alert_status add value if not exists 'resolved';
alter type public.alert_status add value if not exists 'suppressed';

do $$ begin
  create type public.ack_via as enum ('app', 'telegram', 'twilio_keypress', 'sensor');
exception when duplicate_object then null; end $$;
alter type public.ack_via add value if not exists 'app';
alter type public.ack_via add value if not exists 'telegram';
alter type public.ack_via add value if not exists 'twilio_keypress';
alter type public.ack_via add value if not exists 'sensor';

do $$ begin
  create type public.dispatch_channel as enum ('telegram', 'twilio_voice');
exception when duplicate_object then null; end $$;
alter type public.dispatch_channel add value if not exists 'telegram';
alter type public.dispatch_channel add value if not exists 'twilio_voice';

do $$ begin
  create type public.dispatch_status as enum ('queued', 'sending', 'sent', 'delivered', 'answered', 'no_answer', 'failed', 'suppressed', 'dry_run');
exception when duplicate_object then null; end $$;
alter type public.dispatch_status add value if not exists 'queued';
alter type public.dispatch_status add value if not exists 'sending';
alter type public.dispatch_status add value if not exists 'sent';
alter type public.dispatch_status add value if not exists 'delivered';
alter type public.dispatch_status add value if not exists 'answered';
alter type public.dispatch_status add value if not exists 'no_answer';
alter type public.dispatch_status add value if not exists 'failed';
alter type public.dispatch_status add value if not exists 'suppressed';
alter type public.dispatch_status add value if not exists 'dry_run';

do $$ begin
  create type public.suppress_reason as enum ('dedupe', 'lower_tier', 'rate_cap', 'catch_up', 'motion_lock', 'call_cooldown', 'state_unknown', 'acknowledged', 'dry_run');
exception when duplicate_object then null; end $$;
alter type public.suppress_reason add value if not exists 'dedupe';
alter type public.suppress_reason add value if not exists 'lower_tier';
alter type public.suppress_reason add value if not exists 'rate_cap';
alter type public.suppress_reason add value if not exists 'catch_up';
alter type public.suppress_reason add value if not exists 'motion_lock';
alter type public.suppress_reason add value if not exists 'call_cooldown';
alter type public.suppress_reason add value if not exists 'state_unknown';
alter type public.suppress_reason add value if not exists 'acknowledged';
alter type public.suppress_reason add value if not exists 'dry_run';

do $$ begin
  create type public.incident_type as enum ('seatbelt_breach', 'guardian_hazard', 'sos', 'ppe_override', 'near_miss', 'first_aid', 'property_damage', 'manual', 'correction');
exception when duplicate_object then null; end $$;
alter type public.incident_type add value if not exists 'seatbelt_breach';
alter type public.incident_type add value if not exists 'guardian_hazard';
alter type public.incident_type add value if not exists 'sos';
alter type public.incident_type add value if not exists 'ppe_override';
alter type public.incident_type add value if not exists 'near_miss';
alter type public.incident_type add value if not exists 'first_aid';
alter type public.incident_type add value if not exists 'property_damage';
alter type public.incident_type add value if not exists 'manual';
alter type public.incident_type add value if not exists 'correction';

do $$ begin
  create type public.lang as enum ('en', 'hi', 'ta');
exception when duplicate_object then null; end $$;
alter type public.lang add value if not exists 'en';
alter type public.lang add value if not exists 'hi';
alter type public.lang add value if not exists 'ta';

do $$ begin
  create type public.ppe_item as enum ('helmet', 'vest', 'boots', 'gloves');
exception when duplicate_object then null; end $$;
alter type public.ppe_item add value if not exists 'helmet';
alter type public.ppe_item add value if not exists 'vest';
alter type public.ppe_item add value if not exists 'boots';
alter type public.ppe_item add value if not exists 'gloves';

do $$ begin
  create type public.proximity_zone as enum ('awareness', 'warning', 'danger');
exception when duplicate_object then null; end $$;
alter type public.proximity_zone add value if not exists 'awareness';
alter type public.proximity_zone add value if not exists 'warning';
alter type public.proximity_zone add value if not exists 'danger';

do $$ begin
  create type public.anomaly_type as enum ('idle_excess', 'seatbelt_off_moving', 'overspeed', 'slope_exceeded', 'fault_continued_operation', 'hydraulic_temp_drift', 'coolant_temp_drift');
exception when duplicate_object then null; end $$;
alter type public.anomaly_type add value if not exists 'idle_excess';
alter type public.anomaly_type add value if not exists 'seatbelt_off_moving';
alter type public.anomaly_type add value if not exists 'overspeed';
alter type public.anomaly_type add value if not exists 'slope_exceeded';
alter type public.anomaly_type add value if not exists 'fault_continued_operation';
alter type public.anomaly_type add value if not exists 'hydraulic_temp_drift';
alter type public.anomaly_type add value if not exists 'coolant_temp_drift';

do $$ begin
  create type public.alert_kind as enum ('seatbelt_off_moving', 'guardian_hazard', 'proximity_zone', 'ppe_missing', 'anomaly_machine', 'idle_excess', 'sos', 'ledger_tamper', 'alert_flood');
exception when duplicate_object then null; end $$;
alter type public.alert_kind add value if not exists 'seatbelt_off_moving';
alter type public.alert_kind add value if not exists 'guardian_hazard';
alter type public.alert_kind add value if not exists 'proximity_zone';
alter type public.alert_kind add value if not exists 'ppe_missing';
alter type public.alert_kind add value if not exists 'anomaly_machine';
alter type public.alert_kind add value if not exists 'idle_excess';
alter type public.alert_kind add value if not exists 'sos';
alter type public.alert_kind add value if not exists 'ledger_tamper';
alter type public.alert_kind add value if not exists 'alert_flood';

do $$ begin
  create type public.photo_category as enum ('hydraulic_leak', 'fuel_leak', 'coolant_leak', 'tyre_damage', 'structural_crack', 'fire_smoke', 'ppe_issue', 'unknown');
exception when duplicate_object then null; end $$;
alter type public.photo_category add value if not exists 'hydraulic_leak';
alter type public.photo_category add value if not exists 'fuel_leak';
alter type public.photo_category add value if not exists 'coolant_leak';
alter type public.photo_category add value if not exists 'tyre_damage';
alter type public.photo_category add value if not exists 'structural_crack';
alter type public.photo_category add value if not exists 'fire_smoke';
alter type public.photo_category add value if not exists 'ppe_issue';
alter type public.photo_category add value if not exists 'unknown';

do $$ begin
  create type public.machine_health as enum ('ok', 'caution', 'fault');
exception when duplicate_object then null; end $$;
alter type public.machine_health add value if not exists 'ok';
alter type public.machine_health add value if not exists 'caution';
alter type public.machine_health add value if not exists 'fault';
