-- Migration 002 (B4): the generated registry seed, `events` (single source of truth), `emit_event` (the only
-- write path, and the only place that enqueues ledger entries and Loop work), Realtime fan-out per audience,
-- `alerts`, `dispatches` (outbox kicked through pg_net), the training tables the snapshot reads, `my_snapshot`.
-- References: data-model §2.8, §3, §4.2; event-pipeline §0, §8; api-contracts §3, §4, §7.

-- >>> generated: contracts seed (do not edit between the markers)
-- GENERATED by scripts/gen-sql-seed.ts from @cat/shared (contracts). Do not edit by hand.

insert into public.event_types (type, default_tier, ledger, raises_alert, alert_kind, audiences, lesson_code, replay) values
  ('safety.seatbelt_breach', 'warning'::public.alert_tier, true, true, 'seatbelt_off_moving', array['operator', 'supervisor', 'trainer']::public.audience[], 'seatbelt_slopes', true),
  ('safety.seatbelt_resolved', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('safety.overspeed', 'caution'::public.alert_tier, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('safety.slope_exceeded', 'warning'::public.alert_tier, false, false, null, array['operator', 'supervisor', 'trainer']::public.audience[], null, false),
  ('safety.proximity', 'caution'::public.alert_tier, false, true, 'proximity_zone', array['operator', 'supervisor']::public.audience[], null, false),
  ('safety.organiser_alert', 'info'::public.alert_tier, false, false, null, array['supervisor']::public.audience[], null, false),
  ('anomaly.detected', 'caution'::public.alert_tier, false, true, 'anomaly_machine', array['site', 'supervisor']::public.audience[], null, false),
  ('anomaly.cleared', null, false, false, null, array['site', 'supervisor']::public.audience[], null, false),
  ('guardian.hazard_near_operator', 'warning'::public.alert_tier, true, true, 'guardian_hazard', array['operator', 'supervisor', 'trainer']::public.audience[], 'faulty_machine_nearby', false),
  ('guardian.hazard_cleared', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.raised', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.acknowledged', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.escalated', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.resolved', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('alert.suppressed', null, false, false, null, array['supervisor']::public.audience[], null, false),
  ('dispatch.sent', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.delivered', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.answered', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.failed', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('dispatch.suppressed', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('sos.raised', 'critical'::public.alert_tier, true, true, 'sos', array['operator', 'supervisor']::public.audience[], null, false),
  ('sos.cancelled', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('ppe.missing', 'caution'::public.alert_tier, false, true, 'ppe_missing', array['operator', 'supervisor']::public.audience[], null, false),
  ('ppe.restored', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('ppe.override_granted', null, true, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.started', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.paused', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.completed', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.progress', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('task.start_blocked', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('incident.reported', null, true, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('incident.logged', null, false, false, null, array['operator', 'supervisor']::public.audience[], null, false),
  ('operator.motion_lock_changed', null, false, false, null, array['operator']::public.audience[], null, false),
  ('ledger.verified', null, false, false, null, array['supervisor']::public.audience[], null, false),
  ('ledger.tamper_detected', 'critical'::public.alert_tier, false, true, 'ledger_tamper', array['supervisor']::public.audience[], null, false),
  ('ledger.checkpoint_published', null, false, false, null, array['supervisor']::public.audience[], null, false),
  ('training.lesson_assigned', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('training.lesson_completed', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('training.replay_ready', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('training.replay_completed', null, false, false, null, array['operator', 'trainer']::public.audience[], null, false),
  ('scenario.started', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.paused', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.resumed', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.speed_changed', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.jumped', null, false, false, null, array['site']::public.audience[], null, false),
  ('scenario.finished', null, false, false, null, array['site']::public.audience[], null, false),
  ('system.warning', null, false, false, null, array['supervisor']::public.audience[], null, false)
on conflict (type) do update set default_tier = excluded.default_tier, ledger = excluded.ledger,
  raises_alert = excluded.raises_alert, alert_kind = excluded.alert_kind, audiences = excluded.audiences,
  lesson_code = excluded.lesson_code, replay = excluded.replay;
delete from public.event_types where type <> all (array['safety.seatbelt_breach', 'safety.seatbelt_resolved', 'safety.overspeed', 'safety.slope_exceeded', 'safety.proximity', 'safety.organiser_alert', 'anomaly.detected', 'anomaly.cleared', 'guardian.hazard_near_operator', 'guardian.hazard_cleared', 'alert.raised', 'alert.acknowledged', 'alert.escalated', 'alert.resolved', 'alert.suppressed', 'dispatch.sent', 'dispatch.delivered', 'dispatch.answered', 'dispatch.failed', 'dispatch.suppressed', 'sos.raised', 'sos.cancelled', 'ppe.missing', 'ppe.restored', 'ppe.override_granted', 'task.started', 'task.paused', 'task.completed', 'task.progress', 'task.start_blocked', 'incident.reported', 'incident.logged', 'operator.motion_lock_changed', 'ledger.verified', 'ledger.tamper_detected', 'ledger.checkpoint_published', 'training.lesson_assigned', 'training.lesson_completed', 'training.replay_ready', 'training.replay_completed', 'scenario.started', 'scenario.paused', 'scenario.resumed', 'scenario.speed_changed', 'scenario.jumped', 'scenario.finished', 'system.warning']::text[]);

insert into public.alert_policies (kind, hazard_group, tier_default, tier_max, dedupe_window_s, ack_timeout_s, notify_now, escalate_to, rate_capped, needs_ack) values
  ('seatbelt_off_moving', 'seatbelt', 'warning'::public.alert_tier, 'critical'::public.alert_tier, 120, 20, '{}'::text[], array['supervisor_telegram']::text[], false, true),
  ('guardian_hazard', 'guardian', 'warning'::public.alert_tier, 'critical'::public.alert_tier, 60, 15, '{}'::text[], array['operator_call', 'supervisor_telegram']::text[], false, true),
  ('proximity_zone', 'proximity', 'caution'::public.alert_tier, 'warning'::public.alert_tier, 30, 20, '{}'::text[], array['supervisor_telegram']::text[], true, true),
  ('ppe_missing', 'ppe', 'caution'::public.alert_tier, 'caution'::public.alert_tier, 300, null, '{}'::text[], '{}'::text[], true, false),
  ('anomaly_machine', 'machine_health', 'caution'::public.alert_tier, 'caution'::public.alert_tier, 600, null, '{}'::text[], '{}'::text[], true, false),
  ('idle_excess', 'idle', 'info'::public.alert_tier, 'caution'::public.alert_tier, 1800, null, '{}'::text[], '{}'::text[], true, false),
  ('sos', 'sos', 'critical'::public.alert_tier, 'critical'::public.alert_tier, null, 60, array['supervisor_telegram']::text[], array['supervisor_call']::text[], false, true),
  ('ledger_tamper', 'ledger', 'critical'::public.alert_tier, 'critical'::public.alert_tier, 600, null, array['supervisor_telegram']::text[], '{}'::text[], false, false),
  ('alert_flood', 'flood', 'caution'::public.alert_tier, 'caution'::public.alert_tier, 600, null, array['supervisor_telegram']::text[], '{}'::text[], false, false)
on conflict (kind) do update set hazard_group = excluded.hazard_group, tier_default = excluded.tier_default,
  tier_max = excluded.tier_max, dedupe_window_s = excluded.dedupe_window_s, ack_timeout_s = excluded.ack_timeout_s,
  notify_now = excluded.notify_now, escalate_to = excluded.escalate_to, rate_capped = excluded.rate_capped, needs_ack = excluded.needs_ack;
delete from public.alert_policies where kind <> all (array['seatbelt_off_moving', 'guardian_hazard', 'proximity_zone', 'ppe_missing', 'anomaly_machine', 'idle_excess', 'sos', 'ledger_tamper', 'alert_flood']::text[]);

insert into public.explanation_templates (anomaly_type, en, hi) values
  ('idle_excess'::public.anomaly_type, '{machine} idled {idle_pct}% of the last hour, {ratio}× its normal. About {fuel_l} L of diesel (≈ ₹{cost_inr}).', '{machine} पिछले एक घंटे में {idle_pct}% समय खाली चली, सामान्य से {ratio} गुना। लगभग {fuel_l} लीटर डीज़ल (≈ ₹{cost_inr})।'),
  ('seatbelt_off_moving'::public.anomaly_type, '{machine} moved at {speed_kmh} km/h with the seatbelt off on a {pitch_deg}° slope.', '{machine} {pitch_deg}° ढलान पर बिना सीटबेल्ट {speed_kmh} किमी/घंटा चली।'),
  ('overspeed'::public.anomaly_type, '{machine} ran at {speed_kmh} km/h in a {limit_kmh} km/h zone.', '{machine} {limit_kmh} किमी/घंटा ज़ोन में {speed_kmh} किमी/घंटा चली।'),
  ('slope_exceeded'::public.anomaly_type, '{machine} worked on a {pitch_deg}° slope; the limit is {limit_deg}°.', '{machine} {pitch_deg}° ढलान पर चली; सीमा {limit_deg}° है।'),
  ('fault_continued_operation'::public.anomaly_type, '{machine} kept working for {minutes} min with fault {code} active.', '{machine} फ़ॉल्ट {code} के साथ {minutes} मिनट चलती रही।'),
  ('hydraulic_temp_drift'::public.anomaly_type, '{machine} hydraulic oil is at {value}°C, rising above its normal {mean}°C.', '{machine} का हाइड्रोलिक तेल {value}°C है, सामान्य {mean}°C से ऊपर।'),
  ('coolant_temp_drift'::public.anomaly_type, '{machine} coolant is at {value}°C, above its normal {mean}°C.', '{machine} का कूलेंट {value}°C है, सामान्य {mean}°C से ऊपर।')
on conflict (anomaly_type) do update set en = excluded.en, hi = excluded.hi;
-- <<< generated: contracts seed

-- ── Queues owned by the worker (data-model §4.2, §2.8) ─────────────────────────────────────────────
create table if not exists private.ledger_queue (
  id bigint generated always as identity primary key,
  idempotency_key text not null unique,        -- 'ledger:' || events.idempotency_key
  event_id uuid not null,
  entry jsonb not null,                        -- what the drain (B5) canonicalises; the event row is the source
  enqueued_at timestamptz not null default now(),
  written_incident_id uuid,
  error text
);
create index if not exists ledger_queue_pending_idx on private.ledger_queue (id) where written_incident_id is null and error is null;

create table if not exists private.loop_queue (
  event_id uuid primary key,
  enqueued_at timestamptz not null default now(),
  done_at timestamptz,
  error text
);
create index if not exists loop_queue_pending_idx on private.loop_queue (enqueued_at) where done_at is null and error is null;

-- ── 3.1 events ─────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  seq bigint generated always as identity unique,
  run_id uuid references public.scenario_runs(id) on delete cascade,
  type text not null references public.event_types(type),
  tier public.alert_tier,
  sim_ts timestamptz,
  recorded_at timestamptz not null default now(),
  site_id uuid not null references public.sites(id),
  machine_id uuid references public.machines(id),
  operator_id uuid references public.operators(id),
  task_id uuid references public.tasks(id),
  alert_id uuid,                                -- FK to alerts added below (alerts references events too)
  audiences public.audience[] not null check (cardinality(audiences) > 0),
  source text not null check (source in ('detector.rule', 'detector.ewma', 'guardian', 'user', 'director', 'system', 'telegram', 'twilio', 'loader')),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  correlation_id uuid,
  causation_id uuid,
  idempotency_key text not null unique check (length(idempotency_key) between 3 and 200)
);
create index if not exists events_run_seq_idx on public.events (run_id, seq);
create index if not exists events_operator_seq_idx on public.events (operator_id, seq desc);
create index if not exists events_site_seq_idx on public.events (site_id, seq desc);
create index if not exists events_type_idx on public.events (type);
create index if not exists events_machine_idx on public.events (machine_id);
create index if not exists events_task_idx on public.events (task_id);
create index if not exists events_alert_idx on public.events (alert_id);
create index if not exists events_audiences_gin on public.events using gin (audiences);

-- ── 3.2 alerts ─────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.scenario_runs(id) on delete cascade,
  origin_event_id uuid references public.events(id),
  kind text not null references public.alert_policies(kind),
  hazard_key text not null,                     -- {hazard_group}:{operator_id}:{subject}
  tier public.alert_tier not null,
  status public.alert_status not null default 'open',
  operator_id uuid references public.operators(id),
  machine_id uuid references public.machines(id),
  site_id uuid not null references public.sites(id),
  occurrences int not null default 1,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  needs_ack boolean not null default false,
  ack_by uuid,
  ack_at timestamptz,
  ack_via public.ack_via,
  escalate_at timestamptz,
  escalation_level smallint not null default 0,
  suppressed_by uuid references public.alerts(id),
  suppress_reason public.suppress_reason,
  protocol_card_id text references public.protocol_cards(id),
  tier_history jsonb not null default '[]',
  abuse_suspected boolean not null default false,
  updated_at timestamptz not null default now()
);
-- dedupe for everything except SOS: every SOS is its own alert (G2-3)
create unique index if not exists alerts_active_hazard_uidx on public.alerts (hazard_key)
  where status in ('open', 'acknowledged', 'escalating') and kind <> 'sos';
create index if not exists alerts_escalate_idx on public.alerts (escalate_at) where status = 'open' and escalate_at is not null;
create index if not exists alerts_operator_status_idx on public.alerts (operator_id, status);
create index if not exists alerts_site_idx on public.alerts (site_id);
create index if not exists alerts_run_idx on public.alerts (run_id);
create index if not exists alerts_machine_idx on public.alerts (machine_id);
create index if not exists alerts_origin_idx on public.alerts (origin_event_id);
create index if not exists alerts_suppressed_by_idx on public.alerts (suppressed_by);
create index if not exists alerts_protocol_idx on public.alerts (protocol_card_id);
drop trigger if exists alerts_touch on public.alerts;
create trigger alerts_touch before update on public.alerts for each row execute function private.touch_updated_at();
alter table public.events drop constraint if exists events_alert_fk;
alter table public.events add constraint events_alert_fk foreign key (alert_id) references public.alerts(id);

-- ── 3.3 dispatches (outbox) ────────────────────────────────────────────────────────────────────────
create table if not exists public.dispatches (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid references public.alerts(id),
  subject_id uuid,                              -- for rows without an alert (checkpoint, flood summary)
  subject_key uuid generated always as (coalesce(alert_id, subject_id)) stored,
  purpose text not null check (purpose in ('alert', 'escalation', 'ledger_checkpoint', 'flood_summary', 'reminder')),
  channel public.dispatch_channel not null,
  recipient_ref text not null,                  -- name of an Edge Function secret, never a number
  recipient_role public.app_role not null,
  escalation_level smallint not null default 0,
  attempts smallint not null default 0,
  status public.dispatch_status not null default 'queued',
  body jsonb not null default '{}',
  provider_ref text,
  sending_at timestamptz,
  error jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dispatches_subject check (alert_id is not null or subject_id is not null)
);
create unique index if not exists dispatches_once_uidx on public.dispatches (subject_key, purpose, channel, recipient_role, escalation_level);
create index if not exists dispatches_alert_idx on public.dispatches (alert_id);
create index if not exists dispatches_requeue_idx on public.dispatches (sending_at) where status = 'sending' and provider_ref is null;
drop trigger if exists dispatches_touch on public.dispatches;
create trigger dispatches_touch before update on public.dispatches for each row execute function private.touch_updated_at();

-- kick: after insert, or after an update that sets status back to 'queued' (requeue), post {dispatch_id} to the
-- dispatch Edge Function through pg_net (the request is sent after this transaction commits). Secrets from Vault.
create or replace function private.dispatch_kick()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_url text; v_key text; v_dry boolean;
begin
  select decrypted_secret into v_url from vault.decrypted_secrets where name = 'public_functions_url';
  select decrypted_secret into v_key from vault.decrypted_secrets where name = 'supabase_secret_key';
  if v_url is null or v_key is null then
    update public.dispatches set status = 'failed', error = jsonb_build_object('reason', 'vault secrets missing') where id = new.id;
    return new;
  end if;
  perform extensions.net.http_post(
    url := v_url || '/dispatch',
    body := jsonb_build_object('dispatch_id', new.id),
    headers := jsonb_build_object('Content-Type', 'application/json', 'apikey', v_key),
    timeout_milliseconds := 20000);
  return new;
end $$;
drop trigger if exists dispatches_kick on public.dispatches;
create trigger dispatches_kick after insert or update of status on public.dispatches
  for each row when (new.status = 'queued') execute function private.dispatch_kick();

-- ── 2.8 Training tables the snapshot reads (builders arrive in B10b) ───────────────────────────────
create table if not exists public.lessons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  content jsonb not null,                       -- LessonContent
  video_paths jsonb,
  topic_event_types text[] not null default '{}',
  version int not null default 1
);
create table if not exists public.lesson_assignments (
  id uuid primary key default gen_random_uuid(),
  operator_id uuid not null references public.operators(id),
  lesson_id uuid not null references public.lessons(id),
  because_event_id uuid references public.events(id),
  assigned_at timestamptz not null default now(),
  completed_at timestamptz,
  quiz_score numeric(5,1),
  unique nulls not distinct (operator_id, lesson_id, because_event_id)
);
create index if not exists lesson_assignments_lesson_idx on public.lesson_assignments (lesson_id);
create index if not exists lesson_assignments_event_idx on public.lesson_assignments (because_event_id);
create table if not exists public.replay_templates (
  event_type text primary key references public.event_types(type),
  version int not null default 1,
  brief jsonb not null,
  evidence_spec jsonb not null,
  ideal_open_order text[] not null,
  decide_steps jsonb not null,
  correct_protocol_order text[] not null,
  protocol_card_id text not null references public.protocol_cards(id)
);
create table if not exists public.replay_scenarios (
  id uuid primary key default gen_random_uuid(),
  source_event_id uuid not null unique references public.events(id),
  operator_id uuid not null references public.operators(id),
  template_version int not null,
  scenario_json jsonb not null,                 -- ReplayScenario (no answer key)
  answer_key jsonb not null default '{}',       -- relevant/why/correct choices; never selected by clients (column not granted)
  created_at timestamptz not null default now()
);
create index if not exists replay_scenarios_operator_idx on public.replay_scenarios (operator_id);
create table if not exists public.replay_attempts (
  id uuid primary key default gen_random_uuid(),
  replay_id uuid not null references public.replay_scenarios(id),
  operator_id uuid not null references public.operators(id),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  open_order text[] not null default '{}',
  choices jsonb not null default '[]',
  safety_score numeric(5,1),
  procedure_score numeric(5,1),
  efficiency_score numeric(5,1),
  process_trace jsonb
);
create index if not exists replay_attempts_replay_idx on public.replay_attempts (replay_id);
create index if not exists replay_attempts_operator_idx on public.replay_attempts (operator_id);

-- ── emit_event: the only write path (N3), idempotent on idempotency_key ────────────────────────────
create or replace function private.emit_event(
  p_type text, p_payload jsonb, p_idempotency_key text, p_source text, p_site_id uuid,
  p_run_id uuid default null, p_machine_id uuid default null, p_operator_id uuid default null,
  p_task_id uuid default null, p_alert_id uuid default null, p_sim_ts timestamptz default null,
  p_tier public.alert_tier default null, p_correlation_id uuid default null, p_causation_id uuid default null
) returns public.events language plpgsql security definer set search_path = '' as $$
declare et public.event_types%rowtype; ev public.events%rowtype;
begin
  select * into et from public.event_types where type = p_type;
  if not found then raise exception 'unknown event type %', p_type using errcode = 'P0001'; end if;
  insert into public.events (run_id, type, tier, sim_ts, site_id, machine_id, operator_id, task_id, alert_id,
                             audiences, source, payload, correlation_id, causation_id, idempotency_key)
  values (p_run_id, p_type, coalesce(p_tier, et.default_tier), p_sim_ts, p_site_id, p_machine_id, p_operator_id,
          p_task_id, p_alert_id, et.audiences, p_source, p_payload, p_correlation_id, p_causation_id, p_idempotency_key)
  on conflict (idempotency_key) do nothing
  returning * into ev;
  if ev.id is null then
    select * into ev from public.events where idempotency_key = p_idempotency_key;   -- the duplicate returns the original
  end if;
  return ev;
end $$;

-- after insert: fan-out to one private topic per audience, then queue ledger / Loop work and nothing else (N2, N3)
create or replace function private.events_after_insert()
returns trigger language plpgsql security definer set search_path = '' as $$
declare et public.event_types%rowtype; a public.audience; topic text; body jsonb;
begin
  body := to_jsonb(new);
  foreach a in array new.audiences loop
    topic := case a
      when 'operator' then 'op:' || new.operator_id::text
      when 'site' then 'site:' || new.site_id::text
      when 'supervisor' then 'sup:' || new.site_id::text
      when 'trainer' then 'train:' || new.site_id::text end;
    if topic is not null and topic not like '%:' then   -- an operator audience with no operator id has no topic
      perform realtime.send(body, 'event', topic, true);
    end if;
  end loop;
  select * into et from public.event_types where type = new.type;
  if et.ledger then
    insert into private.ledger_queue (idempotency_key, event_id, entry)
    values ('ledger:' || new.idempotency_key, new.id, jsonb_build_object('event_id', new.id, 'type', new.type))
    on conflict (idempotency_key) do nothing;
  end if;
  if et.lesson_code is not null or et.replay then
    insert into private.loop_queue (event_id) values (new.id) on conflict (event_id) do nothing;
  end if;
  return null;
end $$;
drop trigger if exists events_after_insert on public.events;
create trigger events_after_insert after insert on public.events for each row execute function private.events_after_insert();

-- append-only for API roles: only private.purge_run (owner) deletes rehearsal rows
create or replace function private.events_block_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'events are append-only' using errcode = '42501';
end $$;
drop trigger if exists events_no_update on public.events;
create trigger events_no_update before update on public.events for each row execute function private.events_block_mutation();

-- ── RLS ────────────────────────────────────────────────────────────────────────────────────────────
alter table public.events enable row level security;
alter table public.alerts enable row level security;
alter table public.dispatches enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_assignments enable row level security;
alter table public.replay_templates enable row level security;
alter table public.replay_scenarios enable row level security;
alter table public.replay_attempts enable row level security;

-- events: one rule per audience, mirroring the Realtime topics exactly (G2-19)
drop policy if exists events_read on public.events;
create policy events_read on public.events for select to authenticated using (
  ('operator' = any (audiences) and operator_id = (select private.my_operator_id()))
  or ('site' = any (audiences) and site_id = (select private.my_site_id()))
  or ((select private.is_fm()) and site_id = (select private.my_site_id()))
  or ((select private.app_role()) = 'trainer' and 'trainer' = any (audiences))
);
drop policy if exists alerts_read on public.alerts;
create policy alerts_read on public.alerts for select to authenticated
  using (operator_id = (select private.my_operator_id()) or (select private.is_fm()));
drop policy if exists dispatches_read on public.dispatches;
create policy dispatches_read on public.dispatches for select to authenticated using ((select private.is_fm()));
drop policy if exists lessons_read_all on public.lessons;
create policy lessons_read_all on public.lessons for select to authenticated using (true);
drop policy if exists replay_templates_read on public.replay_templates;
create policy replay_templates_read on public.replay_templates for select to authenticated using ((select private.app_role()) = 'trainer');
do $$
declare t text;
begin
  foreach t in array array['lesson_assignments', 'replay_scenarios', 'replay_attempts'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format('create policy %I on public.%I for select to authenticated using (operator_id = (select private.my_operator_id()) or (select private.app_role()) = ''trainer'')', t || '_read', t);
  end loop;
end $$;

-- grants: select only; replay_scenarios without the answer key; events/alerts/dispatches never writable by clients
grant select on public.events, public.alerts, public.dispatches, public.lessons, public.lesson_assignments,
  public.replay_templates, public.replay_attempts to authenticated;
grant select (id, source_event_id, operator_id, template_version, scenario_json, created_at) on public.replay_scenarios to authenticated;
revoke update, delete on public.events from anon, authenticated, service_role;

-- realtime.messages: a role may receive on exactly the topics its events policy covers (api-contracts §7)
drop policy if exists spotter_receive on realtime.messages;
create policy spotter_receive on realtime.messages for select to authenticated using (
  realtime.messages.extension = 'broadcast' and (
    (select realtime.topic()) = 'op:' || (select private.my_operator_id())::text
    or (select realtime.topic()) = 'site:' || (select private.my_site_id())::text
    or ((select private.is_fm()) and (select realtime.topic()) = 'sup:' || (select private.my_site_id())::text)
    or ((select private.app_role()) = 'trainer' and (select realtime.topic()) = 'train:' || (select private.my_site_id())::text)
  )
);

-- ── my_snapshot (api-contracts §4 MySnapshotOut) ───────────────────────────────────────────────────
create or replace function public.my_snapshot()
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  me public.profiles%rowtype; run public.scenario_runs%rowtype; v_machine_id uuid; v_tel text; v_sim_now timestamptz;
  j_tasks jsonb; j_alerts jsonb; j_machine jsonb; j_state jsonb; j_weather jsonb; j_assign jsonb; j_events jsonb; j_site jsonb;
begin
  select * into me from public.profiles where user_id = (select auth.uid());
  if not found then raise exception 'forbidden' using errcode = 'P0001'; end if;
  select * into run from public.scenario_runs where is_current limit 1;
  if run.id is not null then
    v_sim_now := case when run.status = 'playing' then run.sim_anchor + (now() - run.wall_anchor) * run.speed else run.sim_anchor end;
  end if;
  select decrypted_secret into v_tel from vault.decrypted_secrets where name = 'site_emergency_tel';
  select jsonb_build_object('id', s.id, 'name', s.name, 'emergency_tel', v_tel) into j_site from public.sites s where s.id = me.site_id;
  if me.operator_id is not null then
    select machine_id into v_machine_id from public.operator_pairings
      where operator_id = me.operator_id and unpaired_at is null and (run_id = run.id or (run.id is null and run_id is null))
      order by paired_at desc limit 1;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object('id', t.id, 'task_type', t.task_type, 'status', t.status,
      'planned_start', t.planned_start, 'progress_pct', t.progress_pct, 'eta_p50_min', t.eta_p50_min,
      'eta_p90_min', t.eta_p90_min, 'eta_factors', t.eta_factors) order by t.planned_start), '[]')
    into j_tasks
    from public.tasks t
    where (run.id is null or t.run_id = run.id)
      and (t.operator_id = me.operator_id or (me.role in ('fleet_manager', 'trainer') and t.site_id = me.site_id));

  select coalesce(jsonb_agg(jsonb_build_object('alert_id', a.id, 'kind', a.kind, 'tier', a.tier, 'needs_ack', a.needs_ack,
      'escalate_at', a.escalate_at, 'occurrences', a.occurrences, 'protocol_card_id', a.protocol_card_id,
      'upgraded_from', (a.tier_history -> -1 ->> 'from'), 'status', a.status, 'first_seen', a.first_seen)
      order by a.first_seen desc), '[]')
    into j_alerts
    from public.alerts a
    where a.status in ('open', 'acknowledged', 'escalating')
      and (a.operator_id = me.operator_id or (me.role = 'fleet_manager' and a.site_id = me.site_id));

  if v_machine_id is not null then
    select jsonb_build_object('id', m.id, 'code', m.code, 'model_name', mm.name,
        'moving', coalesce(ms.moving, false), 'speed_kmh', coalesce(ms.speed_kmh, 0), 'health', coalesce(ms.health, 'ok'),
        'location', jsonb_build_object('lat', coalesce(extensions.ST_Y(ms.location::extensions.geometry), extensions.ST_Y(s.location::extensions.geometry)),
                                       'lon', coalesce(extensions.ST_X(ms.location::extensions.geometry), extensions.ST_X(s.location::extensions.geometry))),
        'seatbelt_fastened', ms.seatbelt_fastened, 'parking_brake', ms.parking_brake)
      into j_machine
      from public.machines m
      left join public.machine_models mm on mm.id = m.model_id
      left join public.machine_state ms on ms.machine_id = m.id and ms.run_id = run.id
      join public.sites s on s.id = me.site_id
      where m.id = v_machine_id;
  end if;

  if me.operator_id is not null then
    select jsonb_build_object('on_foot', os.on_foot, 'ppe', os.ppe,
        'location', case when os.location is null then null else jsonb_build_object('lat', extensions.ST_Y(os.location::extensions.geometry), 'lon', extensions.ST_X(os.location::extensions.geometry)) end,
        'ts', os.ts, 'motion_locked', os.motion_locked, 'call_allowed', os.call_allowed, 'nearest', os.nearest)
      into j_state
      from public.operator_state os where os.operator_id = me.operator_id and os.run_id = run.id;
  end if;

  select jsonb_build_object('ts', w.ts, 'temperature_c', w.temperature_c, 'wbgt_c', w.wbgt_c, 'wind_chill_c', w.wind_chill_c,
      'wind_kmh', w.wind_kmh, 'forecast_peak_c', w.forecast_peak_c, 'forecast_peak_at', w.forecast_peak_at,
      'source_label', case when w.source = 'open_meteo_archive' then 'Open-Meteo archive, CC BY 4.0 (scenario forecast)' else w.source end)
    into j_weather
    from public.weather_snapshots w
    where w.site_id = me.site_id and (run.id is null or w.run_id = run.id or w.run_id is null)
    order by (w.run_id = run.id) desc nulls last, w.ts desc limit 1;

  select coalesce(jsonb_agg(jsonb_build_object('id', la.id, 'lesson_code', l.code, 'because_event_id', la.because_event_id,
      'replay_id', rs.id) order by la.assigned_at desc), '[]')
    into j_assign
    from public.lesson_assignments la
    join public.lessons l on l.id = la.lesson_id
    left join public.replay_scenarios rs on rs.source_event_id = la.because_event_id and rs.operator_id = la.operator_id
    where la.operator_id = me.operator_id and la.completed_at is null;

  select coalesce(jsonb_agg(to_jsonb(e) order by e.seq desc), '[]') into j_events
    from (select * from public.events e
          where ('operator' = any (e.audiences) and e.operator_id = me.operator_id)
             or ('site' = any (e.audiences) and e.site_id = me.site_id)
             or (me.role = 'fleet_manager' and e.site_id = me.site_id)
             or (me.role = 'trainer' and 'trainer' = any (e.audiences))
          order by e.seq desc limit 50) e;

  return jsonb_build_object(
    'contracts_version', '1.0.0',
    'profile', jsonb_build_object('user_id', me.user_id, 'role', me.role, 'operator_id', me.operator_id, 'site_id', me.site_id, 'language', me.language),
    'server_now', now(),
    'run', case when run.id is null then null else jsonb_build_object('id', run.id, 'status', run.status, 'speed', run.speed, 'sim_now', v_sim_now) end,
    'site', j_site,
    'paired_machine_id', v_machine_id,
    'tasks', j_tasks,
    'active_alerts', j_alerts,
    'machine', j_machine,
    'operator_state', j_state,
    'weather', j_weather,
    'assignments', j_assign,
    'recent_events', j_events);
end $$;
revoke execute on function public.my_snapshot() from public, anon;
grant execute on function public.my_snapshot() to authenticated;
